### ISSUE TITLE
No repl

### ISSUE THREAD

**Issue by kineticz** [simonmichael/haskell-atom-setup#1]
There is no REPL under the Haskell IDE menu, any idea?

I am on macOS with atom 1.12.7.

**Comment by simonmichael** [comment]
Sorry, no idea and I've moved from Atom to Intellij. [Here](https://www.reddit.com/r/haskell/comments/5izxxc/setting_up_a_haskell_development_environment) is the most recent haskell/Atom guide and discussion.

**Comment by kineticz** [comment]
ok. How do you compare Intellij and emacs these days?

**Comment by kineticz** [comment]
Is this the plugin you use? 
https://github.com/rikvdkleij/intellij-haskell

**Comment by simonmichael** [comment]
I flip between them for specific tasks. Intellij helps keep me organised, but emacs is of course better for certain things (eg: custom/multi-shell-window-layouts, macros, some magit operations, working on remote machines).

**Comment by simonmichael** [comment]
Yes, I also tried haskforce earlier this year and they were about equivalent.
